### ISSUE TITLE
Keras dimension incompatibility when trying to create BigPhoney instance

### ISSUE THREAD

**Issue by jsrozner** [repp/big-phoney#4]
> from big_phoney import BigPhoney
> p = BigPhoney()

2020-06-29 17:22:37.950128: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-06-29 17:22:37.965589: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa9bae19a30 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-29 17:22:37.965621: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/anaconda3/envs/nlu/lib/python3.7/site-packages/big_phoney/big_phoney.py", line 15, in __init__
    self.pred_model = PredictionModel()
  File "/usr/local/anaconda3/envs/nlu/lib/python3.7/site-packages/big_phoney/prediction_model.py", line 16, in __init__
    self.training_model, self.encoder, self.decoder = self._build_model()
  File "/usr/local/anaconda3/envs/nlu/lib/python3.7/site-packages/big_phoney/prediction_model.py", line 75, in _build_model
    context = get_context(encoder_outputs, h)
  File "/usr/local/anaconda3/envs/nlu/lib/python3.7/site-packages/big_phoney/prediction_model.py", line 38, in get_context
    context = attn_dot([attention_weights, encoder_outputs])
  File "/usr/local/anaconda3/envs/nlu/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 897, in __call__
    self._maybe_build(inputs)
  File "/usr/local/anaconda3/envs/nlu/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 2416, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "/usr/local/anaconda3/envs/nlu/lib/python3.7/site-packages/tensorflow/python/keras/utils/tf_utils.py", line 316, in wrapper
    output_shape = fn(instance, input_shape)
  File "/usr/local/anaconda3/envs/nlu/lib/python3.7/site-packages/tensorflow/python/keras/layers/merge.py", line 677, in build
    'Chosen axes: %s, %s' % (axes[0], axes[1]))
ValueError: Dimension incompatibility 20 != None. Layer shapes: (None, 20, 1), (None, None, 512). Chosen axes: 1, 1

Any ideas? Tensorflow is version 2.2 and keras is up to date

**Comment by meooow25** [comment]
It works if you change [this line](https://github.com/repp/big-phoney/blob/master/big_phoney/prediction_model.py#L42)
```py
char_inputs = Input(shape=(None,))
```
to
```py
char_inputs = Input(shape=(MAX_CHAR_SEQ_LEN,))
```
