### ISSUE TITLE
Can not run it on windows 10

### ISSUE THREAD

**Issue by vasilyevdm** [repp/big-phoney#6]
All the tensorflow debug seems good, but then I get:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    phoney = BigPhoney()
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37\lib\site-packages\big_phoney-1.0.1-py3.7.egg\big_phoney\big_phoney.py", line 15, in __init__
    self.pred_model = PredictionModel()
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37\lib\site-packages\big_phoney-1.0.1-py3.7.egg\big_phoney\prediction_model.py", line 16, in __init__
    self.training_model, self.encoder, self.decoder = self._build_model()
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37\lib\site-packages\big_phoney-1.0.1-py3.7.egg\big_phoney\prediction_model.py", line 75, in _build_model
    context = get_context(encoder_outputs, h)
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37\lib\site-packages\big_phoney-1.0.1-py3.7.egg\big_phoney\prediction_model.py", line 38, in get_context
    context = attn_dot([attention_weights, encoder_outputs])
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 926, in __call__
    input_list)
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 1098, in _functional_construction_call
    self._maybe_build(inputs)
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2643, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\utils\tf_utils.py", line 323, in wrapper
    output_shape = fn(instance, input_shape)
  File "C:\Users\vasil\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\python\keras\layers\merge.py", line 680, in build
    'Chosen axes: %s, %s' % (axes[0], axes[1]))
ValueError: Dimension incompatibility 20 != None. Layer shapes: (None, 20, 1), (None, None, 512). Chosen axes: 1, 1

**Comment by baozoudeshizi** [comment]
I have the same problem
